name = str("Marifer Tablada")
math_grade = float(90.00)
science_grade = float(87.88)
english_grade = int(93)
status = str("PASSED")

print("Name:", name)
print("Math Grade:", math_grade)
print("Science Grade:", science_grade)
print("English Grade:", english_grade)
print("Status:", status)